[package]
name = 'timeless'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ['staticlib']
name = 'timeless'

[dependencies]
extendr-api = '0.8'
dateparser = '0.2'
chrono = '0.4'
rayon = '1.10'
